# -*- coding: utf-8 -*-
"""Lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usKl4Kcmkv8DybrSacipMtLnOtNapLIs
"""

import matplotlib
import matplotlib.pyplot as plt

def CalculateBuy(LastPrice, AvgPrice, instock):
    if LastPrice < 0.7 * AvgPrice and instock < 30:       #Price dropped significantly and stock is low
        return 15                                         #Order 15
    elif instock < 10:                                    #Stock level is critically low
        return 5                                          #Order 5
    else:                                                 #Stock levels are sufficient
        return 0                                          #No order

#Implementing the trading agent
def TradingAgent(PriceHistory, StockLevels, AvgPrice):
    BuyHistory = []
    for price, instock in zip(PriceHistory, StockLevels):   #Price is significantly lower than the average price
        if price < 0.8 * AvgPrice:                          #20% discount
            if instock < 10:                                #Critically low stock
                tobuy = 10
            else:                                           #Stock level not critically low
                tobuy = 15
        else:
            tobuy = CalculateBuy(price, AvgPrice, instock)  #Custom logic to decide the order quantity
        BuyHistory.append(tobuy)
    return BuyHistory

#Example data
PriceHistory = [600, 500, 545, 430, 410, 640]
StockLevels = [20, 15, 6, 27, 10, 11]
AvgPrice = 600

#Trading Agent
BuyHistory = TradingAgent(PriceHistory, StockLevels, AvgPrice)

plt.figure(figsize=(10, 6))
plt.plot(PriceHistory, label='Price')
plt.plot(StockLevels, label='Stock Levels')
plt.plot(BuyHistory, label='ToBuy', linestyle='--', marker='o')
plt.axhline(0.8 * AvgPrice, color='blue', linestyle='--', label='20% Discount Threshold')
plt.xlabel('Time (Index)')
plt.ylabel('Values')
plt.title('Trading Agent Decision Over Time')
plt.legend()
plt.grid()
plt.show()